### ISSUE TITLE
Supply -j`nproc` to make?

### ISSUE THREAD

**Issue by kindaro** [yurikoles-aur/linux-amd-staging-drm-next-git#5]
I wonder if there is a reason to build on a single core.

The build process takes hours, and most objects are independent, so I would think parallelization would speed the process up significantly.

I tried and it works well.

**Comment by kindaro** [comment]
To be specific, this is the change I propose:

```
% git diff --word-diff @~1 @
diff --git a/PKGBUILD b/PKGBUILD
index 7561f51..df598d1 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -70,7 +70,7 @@ build() {
  cd $_srcname
#mainline: disabled for 5.1-rc5
#make bzImage modules htmldocs
  make {+-j`nproc`+} bzImage modules
}

_package() {
```

**Comment by yurikoles** [comment]
You should specify this in `makepkg.conf` `MAKEFLAGS`, please take a look at official wiki: https://wiki.archlinux.org/index.php/Makepkg#Parallel_compilation

**Comment by kindaro** [comment]
Oh, thanks for letting me know!
