### ISSUE TITLE
Patches are broken. 

### ISSUE THREAD

**Issue by gardotd426** [yurikoles-aur/linux-amd-staging-drm-next-git#7]
Some of the patches are currently broken. 

```
==> Starting prepare()...
Setting version...
Applying patch sphinx-workaround.patch...
patching file Documentation/conf.py
Hunk #1 succeeded at 36 with fuzz 2.
Applying patch gcc10-early-boot-fix.patch...
patching file arch/x86/include/asm/stackprotector.h
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file arch/x86/include/asm/stackprotector.h.rej
patching file arch/x86/kernel/smpboot.c
Hunk #1 succeeded at 264 (offset -2 lines).
patching file arch/x86/xen/smp_pv.c
Hunk #1 succeeded at 94 with fuzz 2 (offset 1 line).
patching file include/linux/compiler.h
Hunk #1 succeeded at 231 with fuzz 2 (offset -125 lines).
patching file init/main.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file init/main.c.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
```

Looks like parts of the GCC patch. Part of it does seem to apply, though, so I'm assuming those might still be needed.

wno-maybe-initialized.patch also seems to have been merged into this branch as well:

```
Applying patch wno-maybe-initialized.patch...
patching file Makefile
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file Makefile.rej
patching file init/Kconfig
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file init/Kconfig.rej
patching file kernel/trace/Kconfig
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file kernel/trace/Kconfig.rej
```

Briefly looking over the relevant files seems to indicate that it has indeed been added to the amd-staging-drm-next agd5f tree, so it looks like you can just flat-out remove that patch. I'm trying to build with only the needed bits of the GCC patch, so we'll see how that goes. I'll update you if it builds and works and all that.

**Comment by tictooc** [comment]
Kernel compiles and runs after removing the wno-maybe-initialized.patch and the stackprotector.h and main.c portions of the gcc10-early-boot-fix.patch.

**Comment by gardotd426** [comment]
Yeah sorry I forgot to repost here that it runs, because it has other issue (fans don't run, there have been some recent changes in the SMU part of the kernel for fan control and now Navi fans don't work, so you might want to check if you have fan control).

**Comment by tictooc** [comment]
I didn't test fan control, but clock and voltage controls are broken on this kernel and the mainline kernel.  Looks to be a similar issue to what was happening on stable kernels>5.7.10 and mainline kernels>5.8-rc6.  The bad patch was reverted for the stable 5.8 kernels.

**Comment by gardotd426** [comment]
What, with `amdgpu.ppfeaturemask=0xffffffff`?

Also, I just checked, and it seems the fan control does work with this kernel, but Alex from AMD had given me some patches to test (the "flickering with more than one monitor" issue is back only this time it happens without ppfeaturemask enabled, and he gave me some patches to try with amd-staging-drm-next-git). Turns out those patches themselves broke fan control. But I'm interested to know what you mean by voltage and clock controls. Also what GPU do you have?

**Comment by tictooc** [comment]
I have a bunch of different AMD GPUs, but currently running a Radeon VII.  See here for info on adjusting clocks. [Issue #1245](https://gitlab.freedesktop.org/drm/amd/-/issues/1245#note_598603)

**Comment by gardotd426** [comment]
Ah, both my current AMD GPUs are Navi (SMU v11) so that would explain why I haven't seen your issue (I got rid of my Polaris card back around 5.5/5.6).

Have you tried building with the patch mcoffin gave you?
