### ISSUE TITLE
CONFIG_SND_HDA_PREALLOC_SIZE is set to 0 resulting in speaker-test errors

### ISSUE THREAD

**Issue by Bednar87** [yurikoles-aur/linux-amd-staging-drm-next-git#8]
Hi,

CONFIG_SND_HDA_PREALLOC_SIZE should be set to a non-zero value (4096 for example) as 0 means unlimited and that results in allocation of too much memory and failures. Speaker-test for example will fail.

Can you please set the value to 4096 to match official arch config?

Thanks

**Comment by yurikoles** [comment]
Fixed in 327e3e406c34f6133c6844a04efbdad7c4f7f783
